apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.8.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
#  http:
#    service:
#      spec:
#        type: LoadBalancer
## Comprobaciones kubectl get elasticsearch
## Pods: kubectl get pods --selector='elasticsearch.k8s.elastic.co/cluster-name=quickstart'
## Logs: kubectl logs -f quickstart-es-default-0
## Password: PASSWORD=$(kubectl get secret quickstart-es-elastic-user -o go-template='{{.data.elastic | base64decode}}')
## Port Forward (minikube): kubectl port-forward service/quickstart-es-http 9200
## Service LB: kubectl patch service quickstart-es-http -p '{"spec": {"type": "LoadBalancer"}}'
