apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-request-developer
spec:
  groups:
    - system:authenticated
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FEQ0NBVkFDQVFBd0l6RVNN
    QkFHQTFVRUF3d0paR1YyWld4dmNHVnlNUTB3Q3dZRFZRUUtEQVJrWlhaegpNSUlCSWpBTkJna3Fo
    a2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBJSThOZmFaUnJLVEd4aU11NXZCCmV3cGM5
    bkV3b0ZhUmZYeVBBT2pDNWwrWVJqMTBNdVBMTHpXVDRRSWdSbmhobFBOaEVVdGQwN3FVMTRCNndQ
    Nm8KTVNHczRpcHdOb2grUWVOdlo0Mk9LRGNreVp0S3hXQ0ZnYVVFaXBDYkwvZk9XdWVDbVJYdWFJ
    dC9YMUE2RFJzZwpGQWNKSXZpQ2NGRGhyc1hSZjh2T0xqSC9xazR2RktJYkdTTERTS1V5Zy81bUVt
    N09uVE41UHJlWXZmRW9nQlIzCmJtUGllbzJiazVsNU5QMTNwaFdtSGplcitxZTlCTlN5c241TjVp
    enJqV25wUmx5VTVCbWNtNG9pZVFzVTBCMTAKQzBLQmxzTGVQNGxsbXpvbGp4eTZzQVRXR1BGUXZn
    d1dFUDdadS9JUXZ1dGlPTDdIaXBQSGo0WTVHVHBBc0xDTgpGd0lEQVFBQm9BQXdEUVlKS29aSWh2
    Y05BUUVMQlFBRGdnRUJBTEVvcnZEYlUwMmV5WDl1eGlrS092ZWpjMzhmCmRSaGFzbzZxK05jRDFn
    MTVYTzIrL0QxVHZVZkdyS0Y4V2RFRTZwdGVOdWUrWUROVHBkdE9XNnk0dVZZVjhoRmgKeUlMWHFK
    d2tyckFzOW1LeElpMWVHakRPWm5QdlB5dmNZc3lnYmRXek9BcnI3SDE5NVhMWmIvUmYwZHB6ZTB3
    TAphMk8yTEdsYVBkbWIwaExRL0lIam0wL2c0WnhsWkJzYXRLWmNZSTBJdjhFVGV0UStCdkdpM1ll
    V0dsWXJOZnJNCkFrNDNQM0pzS3dZRnZ1VWd0S3gyR1hxbFQ4aEJGbWZuZkRIM0RvMWxTdWQ4NUVa
    RFpJTWJFVUwySU53TXM5bisKVHJwY29qY2V4Y0Rma0REUGRKeWN0dTZQaUlDTE51a21kMkcxanVN
    YkpBS0dWZ3ZqcWFiUGU5NmNNZ1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 315569260 # 10 años
  usages:
    - digital signature
    - key encipherment
    - client auth