apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks-cilium-01
  region: eu-west-3
managedNodeGroups:
  - name: cluster-cilum-ng-00
    desiredCapacity: 3
    privateNetworking: true
    taints:
      - key: "node.cilium.io/agent-not-ready"
        value: "true"
        effect: "NoExecute"